### ISSUE TITLE
dev oauth not working.

### ISSUE THREAD

**Issue by engageintellect** [bmdavis419/supabase-sveltekit-2024-tutorial#1]
everything initially appears to work...
* I click login
* click sign in with github
* github oauth window opens where I enter username, password, and then enter a code on my mobile.
* get kicked back to "/" with the following server error:
```
SvelteKitError: Not found: /auth/auth-code-error
    at resolve (/Users/r3dux/Repositories/supabase-sveltekit-2024-tutorial/node_modules/.pnpm/@sveltejs+kit@2.5.18_@sveltejs+vite-plugin-svelte@3.1.1_svelte@5.0.0-next.169_vite@5.3.2/node_modules/@sveltejs/kit/src/runtime/server/respond.js:522:13)
    at resolve (/Users/r3dux/Repositories/supabase-sveltekit-2024-tutorial/node_modules/.pnpm/@sveltejs+kit@2.5.18_@sveltejs+vite-plugin-svelte@3.1.1_svelte@5.0.0-next.169_vite@5.3.2/node_modules/@sveltejs/kit/src/runtime/server/respond.js:322:5)
    at Object.handle (/Users/r3dux/Repositories/supabase-sveltekit-2024-tutorial/src/hooks.server.ts:60:10)
    at Module.respond (/Users/r3dux/Repositories/supabase-sveltekit-2024-tutorial/node_modules/.pnpm/@sveltejs+kit@2.5.18_@sveltejs+vite-plugin-svelte@3.1.1_svelte@5.0.0-next.169_vite@5.3.2/node_modules/@sveltejs/kit/src/runtime/server/respond.js:319:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404,
  text: 'Not Found'
}
```

Here is the console:
<img width="630" alt="Screenshot 2024-07-02 at 12 23 40 AM" src="https://github.com/Davis-Media/supabase-sveltekit-2024-tutorial/assets/61082194/54bfe157-8c2c-463e-b83b-4aafc93a62fe">

I double checked my .env.local, looks fine.
github oath looks fine to me too:

<img width="608" alt="Screenshot 2024-07-02 at 12 29 11 AM" src="https://github.com/Davis-Media/supabase-sveltekit-2024-tutorial/assets/61082194/8e14cf57-16c6-410a-846d-9ceaa4075598">

What am I missing here?

**Comment by engageintellect** [comment]
update: deleting docker contianers and re-running "supabase start" solved my issue.
